import esp32
import random
import os
import ubinascii
import machine
import hmac, hashlib
import json
import struct
from ucryptolib import aes
import ucryptolib


class CryptAes:
    """Uses AES encryption to encrypt Payload/Data before sending using MQTT protocol
    The AES algo uses Cipher Block Chaining (CBC)
    AES encryption correctly requires three things to produce ciphertext:
    a message: Payload/Data which is to be encrypted,
    a key: Piece of information (a parameter) that determines the functional output of a
        cryptographic algorithm. For encryption algorithms, a key specifies transformation
        of plaintext into ciphertext, and vice versa for decryption algorithms.
    initialization vector (IV): Piece of data sent along with the key that modifies the end
        ciphertext result. As the name suggests, it initializes the state of the encryption
        algorithm before the data enters. This protects against attacks like pattern analysis.
        This needs to be DIFFERENT for every message.
        
    Uses sessionID (received from Spinner #2) and Encrypted Data to generate HMAC for 
    authentication of the sending device (Spinner #1)
    SessionID is generated by Spinner #2 by posting to the MQTT topic, SessionID every 1 sec.
    
    HMAC (hash-based message authentication code): Type of message authentication code (MAC)
    involving a cryptographic HASH function and a secret cryptographic key. It may be used to
    simultaneously verify both the data integrity and the authentication of a message.
    """
    
    #-----------------------------------------------COMMON-----------------------------------------------------------#   

    def __init__(self, nodeid, sessionID):
        """
        nodeid     : unique id to identify device or board
        iv         : pseudorandom initialization vector, this needs to be DIFFERENT for every message.
        staticiv   : static initialization vector to obfuscate the randomized
                     initialization vector sent with each message, NOT used for any data
        ivkey      : unique key to encrypt the initialization vector
        datakey    : unique key to encypt the Payload/Data
        passphrase : key to generate the HMAC code for authentication
        
        sessionID  : unique value to identify the current communication session, generated only by Spinner #2
        
        ***********************NOTE******************************
        AES is a block cipher with a block size of 128 bits; that's why it encrypts 16 bytes at a time.        
        The block size of CBC mode of encryption is 16, make sure that any data going into AES
        Encryption is of size 16 bytes.
        """
        self.nodeid     = nodeid
        self.iv         = struct.pack("qq", random.randint(1, 101))
        self.staticiv   = struct.pack("qq", 2)
        self.ivkey      = struct.pack("qq", 4)
        self.datakey    = struct.pack("qq", 8)
        self.passphrase = struct.pack("qq", 16)
        self.sessionID  = sessionID
        
        self.encrypted_nodeid = None
        self.encrypted_iv = None
        self.encrypted_data = None
        
        self.decrypted_nodeid = None
        self.decrypted_iv = None
        self.decrypted_data = None
        
        
        self.iv_aes = aes(self.ivkey, 2, self.staticiv)
        self.data_aes = aes(self.datakey, 2, self.iv)
       

    #------------------------------------SPINNER #1 Needs to Use These Functions--------------------------------------#   
    def encrypt(self, sensor_data):
        """Encrypt each of the current initialization vector (iv), the nodeid, and the sensor_data. 
        using (staticiv, ivkey) for iv and (iv, datakey) for nodeid and sensor_data
        :param sensor_data  : Acceleration X, Acceleration Y, Acceleration Z, and Temperature
        """

        #str_sensor_data = bytes(str(sensor_data[0])+ str(sensor_data[1]) + str(sensor_data[2]), 'utf-8') #probably need to fix this so its 16 bytes or whatever
        str_sensor_data = struct.pack("ffff", sensor_data[0], sensor_data[1], sensor_data[2], sensor_data[3])
        self.encrypted_nodeid = self.data_aes.encrypted(self.nodeid)
        self.encrypted_iv = self.iv_aes.encrypt(self.iv)
        self.encrypted_data = self.data_aes.encrypt(str_sensor_data)
       

    
    def sign_hmac(self, sessionID):
        """Generate HMAC by using passphrase, and combination of encrypted iv, encrypted nodeid, 
        encrypted data, received sessionID.
        :param sessionID: unique value to identify the current communication session
        :return         : generated HMAC
        """
        #hmac_data = bytes(sessionID + self.encrypted_iv + self.encrypted_nodeid + self.encrypted_data, 'utf-8')
        hmac_data = struct.pack("ifff", sessionID, self.encrypted_iv, self.encrypted_nodeid, self.encrypted_data)
        return hmac.new(self.passpharse, msg=hmac_data, digestmod=hashlib.sha224)

        
    def send_mqtt(self, hmac_signed):
        """Prepare the message for MQTT transfer using all of encrypted iv, encrypted nodeid, 
        encrypted data, HMAC. Create the message in JSON format.
        :param hmac_signed  : generated HMAC
        :return             : MQTT message to publish to Spinner #2 on Topic "Sensor_Data"
        """        
        return self.encrypted_iv + self.encrypted_nodeid + self.encrypted_data + hmac_signed
        
    #------------------------------------SPINNER #2 Needs to Use These Functions--------------------------------------#   
    
    
    def verify_hmac(self, payload):
        """Authenticates the received MQTT message. 
        Generate HMAC using passphrase, sessionID, RECEIVED encrypted iv, encrypted nodeid, encrypted data 
        and compare with received hmac inside payload to authenticate.
        :param payload  : received MQTT message from Spinner #1. This includes all encrypted data, nodeid, iv, and HMAC
        :return message : MQTT message to publish to Spinner #1 on Topic "Acknowledge", can be "Failed Authentication" 
                          if verification is unsuccessful
        """
        
        json_data = json.loads(payload)
        
        encrypted_nodeid = json_data["node_id"]
        encrypted_iv = json_data["encrypted_iv"] 
        encrypted_data = json_data["data"]   
        
        #hmac_data = bytes(self.sessionID + encrypted_iv + encrypted_nodeid + encrypted_data, 'utf-8')  
        hmac_data = struct.pack("ifff", self.sessionID, self.encrypted_iv, self.encrypted_nodeid, self.encrypted_data)
        hmac_new = hmac.new(self.passphrase, msg=hmac_data, digestmod=hashlib.sha224)
        
        if hmac_new != json_data["hmac"]:
            return "Failed HMAC Authentication"
        else:
            return "Passed HMAC Authentication"
               
            
    def decrypt(self, payload):
        """Decrypts the each encrypted item of the payload.
        Initialize decryption cipher for each item and and use cipher to decrypt payload items.
        :param payload  : received MQTT message from Spinner #1. This includes all encrypted data, nodeid, iv, and HMAC
        :return         : MQTT message to publish to Spinner #1 on Topic "Acknowledge", can be "Successful Decryption"
        """
        
        
        json_data = json.loads(payload)
        
        encrypted_nodeid = json_data["node_id"]
        encrypted_iv = json_data["encrypted_iv"]    
        encrypted_data = json_data["data"]
        
        self.decrypted_nodeid = self.data_aes.decrypt(encrypted_nodeid)
        self.decrypted_iv = self.iv_aes.decrypt(encrypted_iv)  
        self.decrypted_data = self.data_aes.decrypt(encrypted_data)
        
        #sensor_data[0], sensor_data[1], sensor_data[2], sensor_data[3] = struct.unpack("ffff", self.decrypted_data)
        
        return "Successful Decryption"
        


